#include "J1LogChannels.h"

DEFINE_LOG_CATEGORY(SystemLog)
DEFINE_LOG_CATEGORY(CreatureLog)
DEFINE_LOG_CATEGORY(PlayerLog)
DEFINE_LOG_CATEGORY(MonsterLog)
DEFINE_LOG_CATEGORY(WarriorLog)
DEFINE_LOG_CATEGORY(AssassinLog)
DEFINE_LOG_CATEGORY(ArchorLog)
DEFINE_LOG_CATEGORY(ArrowLog)
DEFINE_LOG_CATEGORY(ItemLog)